document.addEventListener("DOMContentLoaded", async () => {
  const output = document.getElementById("cookie-output");
  const siteUrl = document.getElementById("site-url");
  const cookieCount = document.getElementById("cookie-count");
  const btnCopy = document.getElementById("btn-copy");
  const btnDownload = document.getElementById("btn-download");
  const statusMsg = document.getElementById("status-msg");

  // Get the current active tab
  const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
  const url = new URL(tab.url);
  siteUrl.textContent = url.hostname;

  // Fetch cookies for the current tab's URL
  const cookies = await chrome.cookies.getAll({ url: tab.url });

  if (cookies.length === 0) {
    cookieCount.textContent = "0 cookies found";
    output.value = "";
    output.placeholder = "No cookies found for this site.";
    return;
  }

  cookieCount.textContent = `${cookies.length} cookie${cookies.length !== 1 ? "s" : ""} found`;

  // Convert to Netscape format
  const netscapeCookies = toNetscapeFormat(cookies);
  output.value = netscapeCookies;

  // Copy to clipboard
  btnCopy.addEventListener("click", async () => {
    try {
      await navigator.clipboard.writeText(output.value);
      showStatus("✅ Copied to clipboard!");
    } catch {
      // Fallback
      output.select();
      document.execCommand("copy");
      showStatus("✅ Copied to clipboard!");
    }
  });

  // Download as file
  btnDownload.addEventListener("click", () => {
    const filename = `cookies_${url.hostname}_${formatDate()}.txt`;
    const blob = new Blob([output.value], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = filename;
    a.click();
    URL.revokeObjectURL(a.href);
    showStatus(`✅ Downloaded ${filename}`);
  });

  function showStatus(msg) {
    statusMsg.textContent = msg;
    setTimeout(() => {
      statusMsg.textContent = "";
    }, 2500);
  }
});

/**
 * Converts an array of chrome.cookies.Cookie objects to Netscape cookie file format.
 *
 * Format per line (tab-separated):
 *   domain  flag  path  secure  expiration  name  value
 *
 * - domain:     The domain of the cookie (prefixed with . for domain cookies)
 * - flag:       TRUE if the cookie is accessible to all hosts on the domain, FALSE otherwise
 * - path:       The path of the cookie
 * - secure:     TRUE if the cookie requires HTTPS, FALSE otherwise
 * - expiration: Unix timestamp of expiry (0 for session cookies)
 * - name:       The cookie name
 * - value:      The cookie value
 */
function toNetscapeFormat(cookies) {
  const header = "# Netscape HTTP Cookie File\n# https://curl.se/docs/http-cookies.html\n# This file was generated by Cookie Extractor Chrome Extension.\n\n";

  const lines = cookies.map((cookie) => {
    const domain = cookie.domain.startsWith(".") ? cookie.domain : cookie.domain;
    const flag = cookie.domain.startsWith(".") ? "TRUE" : "FALSE";
    const path = cookie.path || "/";
    const secure = cookie.secure ? "TRUE" : "FALSE";
    const expiration = cookie.expirationDate ? Math.round(cookie.expirationDate) : 0;
    const name = cookie.name;
    const value = cookie.value;

    return [domain, flag, path, secure, expiration, name, value].join("\t");
  });

  return header + lines.join("\n") + "\n";
}

/**
 * Returns a formatted date string for filenames: YYYYMMDD_HHmmss
 */
function formatDate() {
  const now = new Date();
  const pad = (n) => String(n).padStart(2, "0");
  return (
    now.getFullYear() +
    pad(now.getMonth() + 1) +
    pad(now.getDate()) +
    "_" +
    pad(now.getHours()) +
    pad(now.getMinutes()) +
    pad(now.getSeconds())
  );
}
