// Generates the PWA icons (simple art: three "bus lanes" and a green dot) into src/icons.ts as base64 PNGs.
//   node scripts/build-icons.mjs
import fs from "node:fs";
import zlib from "node:zlib";
import path from "node:path";
import { fileURLToPath } from "node:url";
const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");

function png(size, draw) {
  const raw = Buffer.alloc((size * 4 + 1) * size);
  for (let y = 0; y < size; y++) {
    raw[y * (size * 4 + 1)] = 0;
    for (let x = 0; x < size; x++) {
      const SS = 3; let r = 0, g = 0, b = 0, a = 0;
      for (let sy = 0; sy < SS; sy++) for (let sx = 0; sx < SS; sx++) {
        const c = draw((x + (sx + 0.5) / SS) / size, (y + (sy + 0.5) / SS) / size);
        if (c) { r += c[0] * c[3]; g += c[1] * c[3]; b += c[2] * c[3]; a += c[3]; }
      }
      const o = y * (size * 4 + 1) + 1 + x * 4, n = SS * SS;
      raw[o] = a ? Math.round(r / a) : 0; raw[o + 1] = a ? Math.round(g / a) : 0; raw[o + 2] = a ? Math.round(b / a) : 0; raw[o + 3] = Math.round((a / n) * 255);
    }
  }
  const chunk = (type, data) => {
    const len = Buffer.alloc(4); len.writeUInt32BE(data.length);
    const td = Buffer.concat([Buffer.from(type), data]);
    const crc = Buffer.alloc(4); crc.writeUInt32BE(zlib.crc32(td) >>> 0);
    return Buffer.concat([len, td, crc]);
  };
  const ihdr = Buffer.alloc(13); ihdr.writeUInt32BE(size, 0); ihdr.writeUInt32BE(size, 4); ihdr[8] = 8; ihdr[9] = 6;
  return Buffer.concat([Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]), chunk("IHDR", ihdr), chunk("IDAT", zlib.deflateSync(raw)), chunk("IEND", Buffer.alloc(0))]);
}
const BG = [14, 17, 22, 1], CARD = [22, 27, 34, 1], ACC = [88, 166, 255, 1], OK = [63, 185, 80, 1];
const inRound = (x, y, x0, y0, x1, y1, r) => {
  const cx = Math.min(Math.max(x, x0 + r), x1 - r), cy = Math.min(Math.max(y, y0 + r), y1 - r);
  return (x - cx) ** 2 + (y - cy) ** 2 <= r * r;
};
// art spans the middle `k` of the icon (maskable icons keep it inside the 80% safe zone)
const art = (k) => (x, y) => {
  const u = (x - 0.5) / k + 0.5, v = (y - 0.5) / k + 0.5;
  const bars = [[0.22, 0.30, 0.78], [0.22, 0.47, 0.66], [0.22, 0.64, 0.54]];
  for (const [x0, yc, x1] of bars) if (inRound(u, v, x0, yc - 0.045, x1, yc + 0.045, 0.045)) return ACC;
  if ((u - 0.78) ** 2 + (v - 0.64) ** 2 <= 0.06 ** 2) return OK;
  return null;
};
const any = (x, y) => (inRound(x, y, 0, 0, 1, 1, 0.22) ? art(0.82)(x, y) ?? CARD : null);
const maskable = (x, y) => art(0.6)(x, y) ?? BG;
const out = {
  "icon-192.png": png(192, any), "icon-512.png": png(512, any),
  "icon-maskable-512.png": png(512, maskable), "apple-touch-icon.png": png(180, maskable),
};
let ts = "// GENERATED by scripts/build-icons.mjs: the PWA icons as base64 PNGs.\nexport const ICONS: Record<string, string> = {\n";
for (const [k, v] of Object.entries(out)) ts += `  ${JSON.stringify(k)}: ${JSON.stringify(v.toString("base64"))},\n`;
fs.writeFileSync(path.join(root, "src", "icons.ts"), ts + "};\n");
console.log(Object.entries(out).map(([k, v]) => k + " " + v.length + " bytes").join(", "));
