/**
 * API endpoint: /api/subtitles
 */

import type { Env } from '../index';
import { extractToken, validateToken } from '../auth/login';
import { extractVideoData } from '../extraction/player';
import { updateToken } from '../storage/kv';
import { throwInvalidParams, throwMissingAuth } from '../utils/errors';

interface SubtitleFormat {
  vtt: string;
  srt: string;
  json3: string;
}

const FORMAT_PARAMS: Record<keyof SubtitleFormat, string> = {
  vtt: 'vtt',
  srt: 'srv1',
  json3: 'json3',
};

export async function handleApiSubtitles(
  request: Request,
  env: Env
): Promise<Response> {
  // Extract and validate token
  const token = extractToken(request);
  if (!token) {
    throwMissingAuth();
  }
  
  const tokenData = await validateToken(env, token);
  
  // Parse query params
  const url = new URL(request.url);
  const videoId = url.searchParams.get('v');
  const lang = url.searchParams.get('lang');
  const format = (url.searchParams.get('format') || 'vtt') as keyof SubtitleFormat;
  
  if (!videoId) {
    throwInvalidParams('Video ID (v) is required');
  }
  
  if (format && !FORMAT_PARAMS[format]) {
    throwInvalidParams('Invalid format. Use: vtt, srt, or json3');
  }
  
  // Extract video data
  const { playerResponse } = await extractVideoData(videoId, tokenData.youtube_cookies);
  
  // Update last_used
  await updateToken(env, token, { last_used: new Date().toISOString() });
  
  // Build response
  const response: any = {
    video_id: videoId,
    title: playerResponse.videoDetails.title,
    available: playerResponse.captionTracks.map(track => ({
      code: track.languageCode,
      name: track.name,
      auto: track.isAutoGenerated,
    })),
  };
  
  // If language requested, fetch subtitle content
  if (lang) {
    const track = playerResponse.captionTracks.find(
      t => t.languageCode === lang || t.languageCode.startsWith(lang + '-')
    );
    
    if (!track) {
      return new Response(JSON.stringify({
        ...response,
        subtitles: null,
        error: `Language '${lang}' not available`,
      }), {
        headers: { 'Content-Type': 'application/json' },
      });
    }
    
    // Fetch subtitle content
    const subtitleUrl = new URL(track.baseUrl);
    subtitleUrl.searchParams.set('fmt', FORMAT_PARAMS[format]);
    
    const subtitleResponse = await fetch(subtitleUrl.toString(), {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
        'Cookie': tokenData.youtube_cookies,
      },
    });
    
    const content = await subtitleResponse.text();
    
    response.subtitles = {
      lang,
      format,
      content,
    };
  }
  
  return new Response(JSON.stringify(response), {
    headers: { 'Content-Type': 'application/json' },
  });
}
