name: Build and Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Publish project
        run: dotnet publish Nexis.Azure.Utilities/Nexis.Azure.Utilities.csproj -c Release -o publish

      - name: Publish project
        run: dotnet publish AzureDevops.Pipeline.Utilities/AzureDevops.Pipeline.Utilities.csproj -c Release -o publish

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: latest
          tag_name: latest
          prerelease: true
          files: |
            publish/nexutils.exe
            publish/azputils.exe